### ISSUE TITLE
Insecure Wallet

### ISSUE THREAD

**Issue by algokk** [Fantom-foundation/Fantom-PWA-Wallet#206]
I have sent FTM tokens from Metamask (0x0d9ab939Dd25E2336731aDEc847579080eBd09D2) to my PWA wallet:

0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 (TX: https://ftmscan.com/tx/0x79061133445bd6873fba2d44182e803f0bdbce3a210cdac31a12263be074d6b2)

Within 1-2 sec my tokens were forwarded from my fantom wallet automatically to another fantom wallet which I not own: https://ftmscan.com/address/0x1b1979f530c0a93c68f57f412c97bf0fd5e69046

In addition, there is an asset called [testShare](https://ibb.co/brvxBRv) with an amount of 10000 but nobody from the FTM team could tell me what it is. What is the testShare asset? 

I created the wallet in Juli-August without any transactions but there are transactions from [january](https://ibb.co/5TJnnmB). The wallet was already in use from someone else. 

I have contacted several people from the FTM team (Discord, Telegram, Support, Twitter, LinkedIn) and everyone from FTM is saying the same: the PWA wallet is secure.

How it can be secure if

1) My tokens are forwarded to another wallet within 1-2 seconds
2) I never shared my passphrase or connected to a third party. My other tokens from Metamask are still there. Only the token at PWA was stolen. 
3) I have created the wallet in juli-august within the pwa wallet and not in january 
4) There is a testShare asset which I have never created. The assets can only be created from your dev like the [pre-created ](https://ibb.co/CPVCvpV) assets. 
5) I am not even able to do something with the testShare because I will need to pay gas fees. If I send tokens to a wallet it is immediately sent to another wallet which I do not own.

Instead of fixing the issue, warning people or helping me I am getting blocked or my comments were removed and still FTM is saying their system is secure. 

**Update: 10th october 2021** - I have sent 2 FTM to my wallet and again the token were sent to another wallet which I do not own. 
I used the FTM Opera network and sent it directly from Binance to the wallet. Before I sent it I removed the cookies and disconnected Metamask but it had the same problem. 

**Update: 11th october 2021** 
Contacted FTM team again and they are ignoring me. The [testShare](https://ibb.co/brvxBRv) looks like a pre-created asset [list](https://ibb.co/CPVCvpV). The question is how this asset comes into my wallet? 

**Update: 12th october 2021 at 09.:00 GMT+11 time** 
After I contacted the CEO Michael Kong he didn't respond to me. I have checked my wallet again and the testShare asset was [removed](https://ibb.co/VY3gDHx) -  

**Update: 12th october 2021 at 09.:19 GMT+11 time** 
The [testShare](https://ibb.co/Wp7ZGNR) asset appears again on my wallet

**Comment by MKong** [comment]
The account has been used on January, there are transactions at that date:

https://ftmscan.com/tx/0x2318b2a133698dbdf4236dfbacd1e114e81d95e5d97b81092a67ed900950d683

You claim the following:

"I created the wallet in Juli-August without any transactions but there are transactions from january. The wallet was already in use from someone else."

If the wallet really was generated in July or August, and transactions had already existed for that wallet address, they would already have appeared on the chain, meaning they would've shown on the explorers and the PWA wallet. If that were the case, why would you continue to use a wallet that had already been in use (meaning someone else had access to it before you?).

The PWA Wallet uses the standard ETH wallet generator available in Web3 library. lt uses the same key generation method that is used extensively on Ethereum. Theoretically, it is possible to generate collisions on the wallet, but the chance of any collusion occurring is extraordinarily low - **1 in 2^160**. So we can confidently say that a collison did not occur:

https://ethereum.stackexchange.com/questions/1115/how-do-ethereum-clients-generate-unique-addresses

We have not seen the same issues as you have described reported by other users.

The simplest explanation based on what you have described in that someone else has acquired a copy of your private key (or keystore file + decryption password) in some manner, and so you should stop using that wallet.

We have no idea what the "testShare" asset is. Clearly, someone transferred it to your wallet, for whatever reason: https://ftmscan.com/tx/0x3ef4d57734df075a74bb83251fca840b1ba63aaccffd0093da5dc3a07b4ff89a.

**Comment by axiomflux** [comment]
I have exactly the same issue as the user describes. Every unstaked token has been withdrawn to at least eight different addresses by an unknown actor. These withdrawals were also able to take my collateralized wFTM, and if I send even one FTM token to my wallet address it is removed within two seconds.   I have 3 staked lots remaining, but obviously I can't unstake without FTM for the fees, and the actor won't pay the collateral back to enable unstaking. So beyond the ~10,000 FTM siphoned off, the ~17,000 in staking is deadlocked.   Nothing has been taken from my MM wallet, and I believe this problem is due to dusting, as I did click on an asset which appeared in the list of synths. I know that the actor sent a batch of dust tokens to around 200,000 addresses, and I received a deposit.  Like the user above I absent-mindedly clicked on the new token in the synths list out of curiosity.  Is that OK, that having no warning or information from FF about such hazards, interacting with non-solicited deposit to a wallet leads to ~27,000 FTM loss?   Brutal.

**Comment by axiomflux** [comment]
![Baitcoins](https://user-images.githubusercontent.com/106823420/178133631-bef1febb-da7a-4a91-8e1e-6f4b1d328d50.png)

**Comment by axiomflux** [comment]
![Screenshot 2022-05-08 at 18-17-03 Fantom Transaction Hash (Txhash) Details FtmScan](https://user-images.githubusercontent.com/106823420/178133814-d01474d8-dd89-457f-803b-9cd1393f41b1.png)

**Comment by axiomflux** [comment]
![THIEF](https://user-images.githubusercontent.com/106823420/178439325-435247e9-4a8a-48ce-8f29-a697d01e9c4f.png)

Check it out. These are just some address trails stealing from my wallet. Why not do a little probing from the FF end and see the full extent of this? Or maybe it is just the poor fellow above and myself  who are the only ones affected......  
Ohhhh, that's probably it.

**Comment by MKong** [comment]
Hi  @axiomflux, we've investigated the issue. Please see the following below:

The official fWallet can not be used to sign arbitrary transactions, unless the wallet is compromised. The app contains specific functions to do certain things, like send native FTM to other addresses, manage delegation on the SFC, claim rewards from a stake, manage fMint collateral and debt, trade through fUni, and send ERC20 tokens. The wallet has an UI interaction for each of these functions and is able to sign templated transactions to perform them, but nothing else. So for example, you can not use fWallet to call functions on other non-supported contracts, swap tokens, stake on other trading platforms, etc. (like you can with Metamask (MM)).

- If you generate a new wallet on fWallet, its private key is kept encrypted with a password inside the browser storage, bound to the domain name of the wallet, and is handled by the browser’s JavaScript engine. We did try to make things as robust as we could, but it’s generally the least secure way to keep your keys, especially if you use your computer and the browser to do other stuff. A compromised browser, spoofed fWallet, and/or infected computer can leak the private key to an attacker. A domain signing on AWS may decrease the risk of DNS spoofing. We recommend connecting using a hardware wallet such as a ledger.

Some of the most recent attacks on Eth were related to spoofed allowance on ERC20 tokens, but no allowance would allow an attack to un-collateralise wFTMs from fMint, or allow a third party to manipulate native FTMs. The fWallet opens a signing challenge for any transfer (it doesn’t keep your password open for the session), so you would see and interaction if the transfer originated inside the fWallet. However, we recommend not approving any token contract address you are not familiar with.

The fWallet is basically attached to the Explorer API, so you can see all previous existing transactions on a newly created address. It’s because fWallet behaves differently than the MM in this case. On MM, if you restore a key on a browser, you don’t see previous transactions. The MM stores signed transactions in its own database, the web3 does not provide wallet base transaction list. But fWallet does. If you restore your wallet on an empty browser, you instantly see all your transaction history. No need to look for it, it’s right there on the home screen of the wallet.

**Comment by axiomflux** [comment]
Thank you for your response. I can see every transaction that has taken coins from my wallet.  Is there a way to limit transactions to a whitelist of my addresses only so that these bot thefts can be stopped? Kind Regards,Andrew Aquilina From: Michael KongSent: Tuesday, 19 July 2022 10:46To: Fantom-foundation/Fantom-PWA-WalletCc: axiomflux; MentionSubject: Re: [Fantom-foundation/Fantom-PWA-Wallet] Insecure Wallet (#206) Hi @axiomflux, we've investigated the issue. Please see the following below:The official fWallet can not be used to sign arbitrary transactions, unless the wallet is compromised. The app contains specific functions to do certain things, like send native FTM to other addresses, manage delegation on the SFC, claim rewards from a stake, manage fMint collateral and debt, trade through fUni, and send ERC20 tokens. The wallet has an UI interaction for each of these functions and is able to sign templated transactions to perform them, but nothing else. So for example, you can not use fWallet to call functions on other non-supported contracts, swap tokens, stake on other trading platforms, etc. (like you can with Metamask (MM)).If you generate a new wallet on fWallet, its private key is kept encrypted with a password inside the browser storage, bound to the domain name of the wallet, and is handled by the browser’s JavaScript engine. We did try to make things as robust as we could, but it’s generally the least secure way to keep your keys, especially if you use your computer and the browser to do other stuff. A compromised browser, spoofed fWallet, and/or infected computer can leak the private key to an attacker. A domain signing on AWS may decrease the risk of DNS spoofing. We recommend connecting using a hardware wallet such as a ledger.Some of the most recent attacks on Eth were related to spoofed allowance on ERC20 tokens, but no allowance would allow an attack to un-collateralise wFTMs from fMint, or allow a third party to manipulate native FTMs. The fWallet opens a signing challenge for any transfer (it doesn’t keep your password open for the session), so you would see and interaction if the transfer originated inside the fWallet. However, we recommend not approving any token contract address you are not familiar with.The fWallet is basically attached to the Explorer API, so you can see all previous existing transactions on a newly created address. It’s because fWallet behaves differently than the MM in this case. On MM, if you restore a key on a browser, you don’t see previous transactions. The MM stores signed transactions in its own database, the web3 does not provide wallet base transaction list. But fWallet does. If you restore your wallet on an empty browser, you instantly see all your transaction history. No need to look for it, it’s right there on the home screen of the wallet.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by MKong** [comment]
Hi @axiomflux You can try a third-party website such as [unrekt](https://app.unrekt.net/) to remove token contract permissions on Fantom. Please note that this is a third-party website, and the Foundation has no affiliation with it.

**Comment by axiomflux** [comment]
Thank you for your reply.

My main fWallet account is not linked to MM, so I cannot "undo" any
contract approvals.
How is it possible for a malicious actor to uncollateralise wFTM when my
fMint score is below 300%?  I cannot do this.  It implies that the wallet
is vulnerable to code added to the fWallet repo?
In the same way, code has been used to automate the withdrawal of any
positive balance arising from staking rewards and deposits. How is it
possible to gain such authority on ANY wallet?
The transactions resulting from these added functions are all visible in my
wallet as you suggest.  Surely it is possible to counter them with coding
measures that are available to the Fantom team?

I am not a programmer, thus I have no way of knowing where to begin trying
to stop this.

Kind Regards,

Andrew Aquilina

**Comment by techansaari** [comment]
I got the same issue on 28 oct22, I transferred 28k ftm from binance to my trust wallet and after some time all coins are transferred to another account. My other network coins are still there. I do not have very indepth dev knowledge but I have lost all my worth. Thanks to ftm flaw.

**Comment by crackcodesprogramloads** [comment]
The address 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 is a Hardhat Node address. You must have added it to you wallet and then later on thought it was an account that you created. Bots are always searching these test wallets for coins that people send to the mainnet by mistake.
